/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ver_1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Dictionary;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.ButtonModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author phixuanhoan
 */
public class formMain extends javax.swing.JFrame {
    // Open = 1, save = 2
    
    //Khời tạo từ điển
    dictionary Dictionaty = new dictionary();

    //Danh sách hiển thị từ tiéng anh
    DefaultListModel dlmEnglish = new DefaultListModel();
    // danh sách hiển thị từ tiếng việt
    DefaultListModel dlmNghia = new DefaultListModel();
    /**
     * Creates new form formMain
     */
    public formMain() {
        initComponents();
        areaExample.setLineWrap(true);
        areaExample.setWrapStyleWord(true);
        areaExplainExample.setLineWrap(true);
        areaExplainExample.setWrapStyleWord(true);
//       listNghia.ensureIndexIsVisible(dlmVietNam.size() - 1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnDeleteWord = new javax.swing.JButton();
        btnAddWord = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        listVietNam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEnglish = new javax.swing.JList<>();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtSpelling = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtExplain = new javax.swing.JTextField();
        txtTranscription = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnShowWord = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaExample = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaExplainExample = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNghia = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        fileOpen = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        btnDeleteWord.setBackground(new java.awt.Color(255, 51, 0));
        btnDeleteWord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDeleteWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/database_remove.png"))); // NOI18N
        btnDeleteWord.setText("Xoá từ đang hiển thị");
        btnDeleteWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteWordActionPerformed(evt);
            }
        });

        btnAddWord.setBackground(new java.awt.Color(51, 255, 51));
        btnAddWord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/add.png"))); // NOI18N
        btnAddWord.setText("Thêm từ");
        btnAddWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddWordMouseClicked(evt);
            }
        });
        btnAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/search_add.png"))); // NOI18N
        jButton3.setText("Tìm Kiếm");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(103, 20));

        listVietNam.setBackground(new java.awt.Color(204, 255, 204));
        listVietNam.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listVietNam.setForeground(new java.awt.Color(0, 0, 153));
        listVietNam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listVietNam.setIcon(new javax.swing.ImageIcon("/Users/phixuanhoan/Desktop/Icons/PNG_Button/png1/24x24/archive.png")); // NOI18N
        listVietNam.setText("Nghĩa của từ");
        listVietNam.setToolTipText("");
        listVietNam.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("   Kiểu tìm kiếm");
        jLabel3.setToolTipText("");
        jLabel3.setBounds(new java.awt.Rectangle(10, 100, 100, 100));
        jLabel3.setOpaque(true);

        listEnglish.setBackground(new java.awt.Color(255, 255, 204));
        listEnglish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listEnglishMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listEnglish);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.setText("Nhập từ cần tìm kiếm ... ");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchMouseExited(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/archive.png"))); // NOI18N
        jLabel4.setText("Từ Tiếng Anh");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Kiểu tìm kiếm -", "1. tuyệt đối", "2. tương đối", " " }));

        txtSpelling.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("   Từ");
        jLabel5.setToolTipText("");
        jLabel5.setName(""); // NOI18N
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("   Nghĩa từ");
        jLabel6.setToolTipText("");
        jLabel6.setOpaque(true);

        txtExplain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTranscription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton4.setBackground(new java.awt.Color(0, 102, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/remove.png"))); // NOI18N
        jButton4.setText("Xoá từ");

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/rss_edit.png"))); // NOI18N
        jButton5.setText("Sửa từ");

        btnShowWord.setBackground(new java.awt.Color(102, 255, 255));
        btnShowWord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnShowWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/database_down.png"))); // NOI18N
        btnShowWord.setText("Hiển tự từ vừa load");
        btnShowWord.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnShowWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowWordActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 0));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/warning.png"))); // NOI18N
        btnExit.setText("Thoát ");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("   Phiên âm");
        jLabel7.setToolTipText("");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("   Câu ví dụ");
        jLabel8.setToolTipText("");
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("  Nghĩa câu ví dụ");
        jLabel9.setToolTipText("");
        jLabel9.setOpaque(true);

        areaExample.setColumns(20);
        areaExample.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        areaExample.setRows(10);
        areaExample.setAutoscrolls(false);
        jScrollPane3.setViewportView(areaExample);

        areaExplainExample.setColumns(20);
        areaExplainExample.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        areaExplainExample.setRows(10);
        areaExplainExample.setAutoscrolls(false);
        jScrollPane4.setViewportView(areaExplainExample);

        listNghia.setBackground(new java.awt.Color(255, 255, 204));
        listNghia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNghiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listNghia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTranscription, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtExplain, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSpelling, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(listVietNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listVietNam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSpelling, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtExplain, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTranscription, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );

        jTabbedPane1.addTab("Tuỳ chọn", jPanel1);

        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Học từ vựng", jPanel2);

        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("File");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        fileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fileOpen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fileOpen.setForeground(new java.awt.Color(0, 0, 153));
        fileOpen.setText("Open");
        fileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenActionPerformed(evt);
            }
        });
        jMenu1.add(fileOpen);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Save.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(0, 0, 153));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 0, 153));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tuỳ chọn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void fileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenActionPerformed
        // TODO add your handling code here:
         try {
           Dictionaty.operateFile("Mở tệp", Dictionaty.FILE_OPEN, 1);
           Dictionaty.setTotalWord(Dictionaty.listWord.size());
        } catch (IOException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        showWordFromFile();
        
        
    }//GEN-LAST:event_fileOpenActionPerformed
    /**
    * Hàm hiển thị từ đã load từ file
    */
    public void showWordFromFile(){
        listEnglish.removeAll();
        listNghia.removeAll();
        if (Dictionaty.getTotalWord() == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn file load dữ liệu");
        } else {
            for (int i = 0; i < Dictionaty.getTotalWord(); i++) {
                dlmEnglish.addElement(i + ": " + Dictionaty.listWord.get(i).getSpelling());
                dlmNghia.addElement(i + ": " + Dictionaty.listWord.get(i).getExplain());
            }
            listEnglish.setModel(dlmEnglish);
            listNghia.setModel(dlmNghia);
        }
    }
    /**
    * Hàm xoá từ đã được hiển thị
    */
    public void removeAllWord(boolean ShowMessage){
        if(dlmNghia.size() != 0){
            listEnglish.getSelectionModel().clearSelection();
            dlmNghia.removeAllElements();
            dlmEnglish.removeAllElements();
            listEnglish.removeAll();
            listNghia.removeAll();
        }else{
            if(ShowMessage == true){
                JOptionPane.showMessageDialog(null, "Danh sách trống ! Không có phần tử để xoá ");
            }
        }
    }
    
    /**
    * Hàm này sẽ xoá tất cả từ đang hiển thị trên list
    */
    private void btnDeleteWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteWordActionPerformed
         removeAllWord(true);
    }//GEN-LAST:event_btnDeleteWordActionPerformed

    private void btnShowWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowWordActionPerformed
        if(dlmEnglish.size() == 0 && dlmNghia.size() == 0){
            showWordFromFile();
        }else{
            JOptionPane.showMessageDialog(null, "Danh sách từ đã được hiển thị !");
        }
    }//GEN-LAST:event_btnShowWordActionPerformed
    /**
    * Thoát bằng button thoát
    */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         int checkExit = JOptionPane.showConfirmDialog(this, "Bạn có chắc là sẽ thoát ứng dụng","Close app ?",JOptionPane.YES_NO_OPTION);
         if(checkExit ==0){
             System.exit(0);
         }else{
             setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
         }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        resetTxt();
        removeAllWord(false);
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseExited
        if(txtSearch.getText().equals("")){
            txtSearch.setText("Nhập từ cần tìm kiếm ...");
        }
    }//GEN-LAST:event_txtSearchMouseExited
    /**
    * Seach theo key
    */
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        removeAllWord(false);
        String keyWord = txtSearch.getText();
        for (int i = 0; i < Dictionaty.getTotalWord(); i++) {
            if (Dictionaty.listWord.get(i).getSpelling().startsWith(keyWord)) {
                dlmEnglish.addElement((i) +": " + Dictionaty.listWord.get(i).getSpelling());
                dlmNghia.addElement((i) +": " +Dictionaty.listWord.get(i).getExplain());
             
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int checkExit = JOptionPane.showConfirmDialog(this, "Bạn có chắc là sẽ thoát ứng dụng","Close app ?",JOptionPane.YES_NO_OPTION);
        if (checkExit == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void listEnglishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listEnglishMouseClicked
        String selected  = listEnglish.getSelectedValue().toString();
        String[] arrTmp = selected.split(":");
        int indexSelected = Integer.parseInt(arrTmp[0]);
        listNghia.setSelectedIndex(indexSelected );
        
        loadInfoToTextBox(indexSelected);
        
    }//GEN-LAST:event_listEnglishMouseClicked

    private void listNghiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNghiaMouseClicked
           // TODO add your handling code here:
        String selected  = listNghia.getSelectedValue().toString();
        String[] arrTmp = selected.split(":");
        int indexSelected = Integer.parseInt(arrTmp[0]);
        listEnglish.setSelectedIndex(indexSelected );
        
        loadInfoToTextBox(indexSelected);
    }//GEN-LAST:event_listNghiaMouseClicked
    // Chức năng thêm sửa xoá
    
    private void btnAddWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddWordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddWordMouseClicked

    private void btnAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordActionPerformed
        // TODO add your handling code here:
        String textSpelling = txtSpelling.getText();
        String textExplain = txtExplain.getText();
        String textTranscription = txtTranscription.getText();
        String textExample = areaExample.getText();
        String textExplainExample = areaExplainExample.getText();
        boolean flagAdd = true;
        String Message = "";
        if(textSpelling.equals("")){
             Message += "Từ không được rỗng ! \n";
            flagAdd = false;
        }
        if(textExplain.equals("")){
            Message += "Nghĩa không được rỗng! \n";
            flagAdd = false;
        }
        if(textTranscription.equals("")){
            Message += "Phiên âm không được rỗng! \n";
            flagAdd = false;
        }
        if(textExample.equals("")){
            Message += "Câu ví dụ không được rỗng! \n";
            flagAdd = false;
        }
        if(textExplainExample.equals("")){
            Message += "Nghĩa câu ví dụ không được rỗng! \n";
            flagAdd = false;
        }
        if(flagAdd == false){
            JOptionPane.showMessageDialog(null, Message);
        }else{
            boolean checkExistWord = Dictionaty.existWord(textSpelling);
            if(checkExistWord == true){
                JOptionPane.showMessageDialog(null, "Từ này đã tồn tại !");
            }else{
                newWord word = new newWord(textSpelling, textExplain,textTranscription, textExample, textExplainExample);
                Dictionaty.listWord.add(word);
                Dictionaty.setTotalWord(Dictionaty.listWord.size());
                showWordFromFile();
            }
        }
    }//GEN-LAST:event_btnAddWordActionPerformed

    //Ngày 13/9/2018 chức năng thêm
    
    public void loadInfoToTextBox(int indexSelected){
        txtSpelling.setText(Dictionaty.listWord.get(indexSelected).getSpelling());
        txtExplain.setText(Dictionaty.listWord.get(indexSelected).getExplain());
        txtTranscription.setText(Dictionaty.listWord.get(indexSelected).getTranscription());
        areaExample.setText(Dictionaty.listWord.get(indexSelected).getExample());
        areaExplainExample.setText(Dictionaty.listWord.get(indexSelected).getExlainExample());
    }
    public void  resetTxt(){
        txtSpelling.setText("");
        txtExplain.setText("");
        txtTranscription.setText("");
        areaExample.setText("");
        areaExplainExample.setText("");
    }
    /**
    * read FIle
    */
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Save;
    private javax.swing.JTextArea areaExample;
    private javax.swing.JTextArea areaExplainExample;
    private javax.swing.JButton btnAddWord;
    private javax.swing.JButton btnDeleteWord;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnShowWord;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JMenuItem fileOpen;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listEnglish;
    private javax.swing.JList<String> listNghia;
    private javax.swing.JLabel listVietNam;
    private javax.swing.JTextField txtExplain;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSpelling;
    private javax.swing.JTextField txtTranscription;
    // End of variables declaration//GEN-END:variables
}
